### PR TITLE
RaunakJasrasaria.md

### PR DESCRIPTION
**Pull request by RaunakJasrasaria**
Blog explaining about DevOps

### CODE REVIEW

**Comment by ShaileshKumar007** [comment]
Kindly follow the guidelines while naming your file

**Comment by RaunakJasrasaria** [comment]
Changed the name to the required format

**Comment by ShaileshKumar007** [comment]
The name of your file should be your username.md. Look at the naming convention of file in readme

**Comment by ShaileshKumar007** [comment]
I'm closing this PR now

**Pull request closed without merging**
