### PR TITLE
ashirvadpandey.md

### PR DESCRIPTION
**Pull request by ashirvadpandey**

### CODE REVIEW

**Comment by ShaileshKumar007** [comment]
Thank You for your contribution.
Kindly format your blog properly

**Comment by ashirvadpandey** [comment]
I have update the file .
please check...

**Comment by ShaileshKumar007** [comment]
Please use the # for the headings. 
eg. # Heading

**Comment by ashirvadpandey** [comment]
i have updated ..
please check

**Comment by ShaileshKumar007** [comment]
It's still not properly formatted.
Please visit [this link](https://www.markdownguide.org/cheat-sheet/) in order to learn more about Markdown files syntax

**Comment by ashirvadpandey** [comment]
Sorry...but i am not getting ,what you are aksing..
i have follow  all rules of bloging

**Comment by ashirvadpandey** [comment]
i have correct the formate ....
please check ..

**Review by ShaileshKumar007 — APPROVED** [review]
Your blog looks good to me.

Thanks for your contribution.

**Comment by ashirvadpandey** [comment]
Hlo there...

This merged status is not showing in hacktoberfest profile....
Please check and update

Thanks

**Pull request merged**
